var read=require("readline-sync")
var util=require('../Object Oriented program/Utility/oppsutil.js')
var file=require('fs')
var companyfile=file.readFileSync('./JSON_FIle/companylist.json', 'utf8')
var companydata = JSON.parse(companyfile)
console.log("List of Comany")
console.log("Press 1 for Google")
console.log("Pree 2 for Facebook")
var option=read.questionInt("Enter the Number : ")
util.stock(option,data)